nodeLinker: node-modules
npmPreapprovedPackages:
  - "@base-ui/react"
  - "@microfeed/theme-kit"
  - "@tailwindcss/vite"
  - "@types/node"
  - "@types/react"
  - "@types/react-dom"
  - "@vitejs/plugin-react"
  - "class-variance-authority"
  - "clsx"
  - "lucide-react"
  - "react"
  - "react-dom"
  - "shadcn"
  - "tailwind-merge"
  - "tailwindcss"
  - "typescript"
  - "vite"
